version: '3.8'
services:
      postgres:
        image: postgres:10.3
        restart: always
        environment:
          - POSTGRES_USER=jeff.barbosa
          - POSTGRES_PASSWORD=jeff.barbosa
        volumes:
          - postgres:/var/lib/postgresql/data
        ports:
          - '5432:5432'
volumes:
      postgres: